"""initial schema

Revision ID: 20c265ea370d
Revises: 
Create Date: 2026-07-25 01:11:13.169634

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.seed_templates import SEED_GREETING_TEMPLATES

revision: str = '20c265ea370d'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_meta',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_meta'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), server_default='he', nullable=False),
    sa.Column('timezone', sa.String(), server_default='Asia/Jerusalem', nullable=False),
    sa.Column('date_format', sa.String(), server_default='DD/MM/YYYY', nullable=False),
    sa.Column('time_format', sa.String(), server_default='24h', nullable=False),
    sa.Column('default_notify_time', sa.String(), server_default='09:00', nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('silent_notifications', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('show_hebrew_date', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('daily_digest_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('digest_time', sa.String(), server_default='08:00', nullable=False),
    sa.Column('list_sort', sa.String(), server_default='upcoming', nullable=False),
    sa.Column('list_filter', sa.String(), nullable=True),
    sa.Column('adar_policy', sa.String(), server_default='adar_ii', nullable=False),
    sa.Column('feb29_policy', sa.String(), server_default='feb28', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('bot_blocked_by_user', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('onboarded', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("adar_policy IN ('adar_i','adar_ii')", name=op.f('ck_users_adar_policy_valid')),
    sa.CheckConstraint("date_format IN ('DD/MM/YYYY','DD.MM.YYYY','YYYY-MM-DD')", name=op.f('ck_users_df_valid')),
    sa.CheckConstraint("feb29_policy IN ('feb28','mar01')", name=op.f('ck_users_feb29_policy_valid')),
    sa.CheckConstraint("language IN ('he','en')", name=op.f('ck_users_lang_valid')),
    sa.CheckConstraint("list_sort IN ('upcoming','name','age','created')", name=op.f('ck_users_list_sort_valid')),
    sa.CheckConstraint("time_format IN ('24h','12h')", name=op.f('ck_users_tf_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('backups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('events_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("format IN ('db','json','csv','xlsx')", name=op.f('ck_backups_backup_format_valid')),
    sa.CheckConstraint("kind IN ('auto','manual','export')", name=op.f('ck_backups_backup_kind_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_backups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backups'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), server_default='birthday', nullable=False),
    sa.Column('custom_type_label', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('category', sa.String(), server_default='other', nullable=False),
    sa.Column('calendar_type', sa.String(), server_default='gregorian', nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('photo_file_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('next_occurrence', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("calendar_type IN ('gregorian','hebrew')", name=op.f('ck_events_calendar_type_valid')),
    sa.CheckConstraint("category IN ('family','friends','work','clients','school','other')", name=op.f('ck_events_category_valid')),
    sa.CheckConstraint("event_type IN ('birthday','anniversary','wedding','memorial','custom')", name=op.f('ck_events_event_type_valid')),
    sa.CheckConstraint("gender IS NULL OR gender IN ('m','f','other')", name=op.f('ck_events_gender_valid')),
    sa.CheckConstraint('day BETWEEN 1 AND 31', name=op.f('ck_events_day_range')),
    sa.CheckConstraint('month BETWEEN 1 AND 13', name=op.f('ck_events_month_range')),
    sa.CheckConstraint('year IS NULL OR (year BETWEEN 1900 AND 2100) OR (year BETWEEN 5660 AND 5860)', name=op.f('ck_events_year_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_name', 'events', ['user_id', 'first_name', 'last_name'], unique=False)
    op.create_index(
        'ix_events_next',
        'events',
        ['next_occurrence'],
        unique=False,
        sqlite_where=sa.text('deleted_at IS NULL AND is_active = 1'),
    )
    op.create_index(
        'ix_events_user',
        'events',
        ['user_id'],
        unique=False,
        sqlite_where=sa.text('deleted_at IS NULL'),
    )
    op.create_index('ix_events_user_month', 'events', ['user_id', 'month'], unique=False)
    op.create_index('ix_events_user_next', 'events', ['user_id', 'next_occurrence'], unique=False)

    op.create_table('greeting_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.CheckConstraint("event_type IN ('birthday','anniversary','wedding','memorial','custom')", name=op.f('ck_greeting_templates_tpl_event_type_valid')),
    sa.CheckConstraint("gender IS NULL OR gender IN ('m','f')", name=op.f('ck_greeting_templates_tpl_gender_valid')),
    sa.CheckConstraint("language IN ('he','en')", name=op.f('ck_greeting_templates_tpl_lang_valid')),
    sa.CheckConstraint("tone IN ('warm','funny','formal','short')", name=op.f('ck_greeting_templates_tpl_tone_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_greeting_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_greeting_templates'))
    )
    op.create_table('reminder_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('offset_days', sa.Integer(), nullable=True),
    sa.Column('offset_minutes', sa.Integer(), nullable=True),
    sa.Column('send_time', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(offset_days IS NOT NULL) <> (offset_minutes IS NOT NULL)', name=op.f('ck_reminder_rules_exactly_one_offset')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_reminder_rules_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminder_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_rules'))
    )
    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.create_index('ix_rules_event', ['event_id'], unique=False)
        batch_op.create_index('ix_rules_user', ['user_id', 'enabled'], unique=False)

    op.create_table('notifications_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("status IN ('pending','sent','failed','skipped')", name=op.f('ck_notifications_log_notif_status_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notifications_log_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['reminder_rules.id'], name=op.f('fk_notifications_log_rule_id_reminder_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_log')),
    sa.UniqueConstraint('event_id', 'rule_id', 'occurrence_date', name='uq_notif')
    )
    with op.batch_alter_table('notifications_log', schema=None) as batch_op:
        batch_op.create_index('ix_notif_sched', ['status', 'scheduled_at'], unique=False)

    # ### end Alembic commands ###

    greeting_templates = sa.table(
        'greeting_templates',
        sa.column('user_id', sa.Integer()),
        sa.column('event_type', sa.String()),
        sa.column('tone', sa.String()),
        sa.column('gender', sa.String()),
        sa.column('language', sa.String()),
        sa.column('body', sa.String()),
        sa.column('is_active', sa.Boolean()),
    )
    op.bulk_insert(
        greeting_templates,
        [
            {
                'user_id': None,
                'event_type': event_type,
                'tone': tone,
                'gender': gender,
                'language': language,
                'body': body,
                'is_active': True,
            }
            for event_type, tone, gender, language, body in SEED_GREETING_TEMPLATES
        ],
    )

    app_meta = sa.table('app_meta', sa.column('key', sa.String()), sa.column('value', sa.String()))
    op.bulk_insert(app_meta, [{'key': 'schema_version', 'value': '1'}])


def downgrade() -> None:
    op.execute("DELETE FROM greeting_templates WHERE user_id IS NULL")
    op.execute("DELETE FROM app_meta WHERE key = 'schema_version'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications_log', schema=None) as batch_op:
        batch_op.drop_index('ix_notif_sched')

    op.drop_table('notifications_log')
    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_rules_user')
        batch_op.drop_index('ix_rules_event')

    op.drop_table('reminder_rules')
    op.drop_table('greeting_templates')
    op.drop_index('ix_events_user_next', table_name='events')
    op.drop_index('ix_events_user_month', table_name='events')
    op.drop_index('ix_events_user', table_name='events')
    op.drop_index('ix_events_next', table_name='events')
    op.drop_index('ix_events_name', table_name='events')

    op.drop_table('events')
    op.drop_table('backups')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_time')

    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('app_meta')
    # ### end Alembic commands ###
